# Project information
site_name: "KeybrL's Blog"
site_url: 'http://blog.keybrl.ink/'
repo_url: 'https://github.com/Keyboard-l/my_Blog-2018plus/'
repo_name: 'Keyboard-l/my_Blog-2018plus'
edit_uri: ''
site_description: 'This site is the Blog of KeybrL.'
site_author: 'KeybrL'
copyright: 'Copyright &copy; 2018-2019 <a href="https://blog.keybrl.ink/">keybrl.ink</a> All Rights Reserved.'
#google_analytics: null
remote_branch: gh-pages
#remote_name: origin

# Documentation layout
pages:
    - Home: 'index.md'
    - Post:
        - '从冯·诺依曼体系结构起航': 'Post/2016-10-22-John-Von-Nouma.md'
        - 'Markdown语法基础': 'Post/2016-11-13-The-base-of-grammar-in-Markdown.md'
        - 'C语言上机心得': 'Post/2016-12-30-C-study.md'
        - '使用Python的smtplib和email发送邮件': 'Post/2017-04-09-Use-smtplib-and-email-in-python-to-send-email.md'





# Build directories
theme:
    name: 'material'
    language: 'zh'
    logo:
        icon: 'code'
    palette:
        primary: 'teal'
        accent: 'teal'
#docs_dir: 'docs'
#site_dir: 'site'
#extra_css: []
#extra_javascript: []
#extra_templates: []
extra:
    search:
        language: 'en, jp'
    repo_icon: 'github'

# Preview controls
#use_directory_urls: true
#strict: false
dev_addr: 0.0.0.0:80

# Formatting options
#markdown_extensions: []
#plugins: ['search']
