site_name: KeybrL's Blog
theme:
    name: 'material'
    language: 'zh'
    logo:
        icon: 'code'
    palette:
        primary: 'teal'
        accent: 'teal'
extra:
    search:
        language: 'en, jp'
    repo_icon: 'github'
site_dir: 'docs'
docs_dir: '_docs'
repo_name: 'Keyboard-l/my_Blog-2018plus'
repo_url: 'https://github.com/Keyboard-l/my_Blog-2018plus/'
