# Project information
site_name: "KeybrL's Blog"
site_url: 'http://blog.keybrl.ink/'
repo_url: 'https://github.com/keybrl/my_Blog-2018plus/'
repo_name: 'keybrl/my_Blog-2018plus'
edit_uri: ''
site_description: 'This site is the Blog of KeybrL.'
site_author: 'KeybrL'
copyright: 'Copyright &copy; <a href="https://blog.keybrl.ink/">keybrl.ink</a> All Rights Reserved.'
google_analytics: ['UA-119555935-1', 'blog.keybrl.ink']
remote_branch: gh-pages
#remote_name: origin

# Documentation layout
pages:
    - Home: 'index.md'
    - Posts:
        - '<b>无聊所作 - 导读</b>': 'posts/index.md'
        - 'Python-Markdown支持的Markdown扩展（未完成）': 'posts/2018-05-24-python-markdown.md'
        - '通过MkDocs搭建个人博客': 'posts/2018-05-19-mkdocs-blog.md'
        - 'HTTP/1.1 - 状态码定义（翻译）（未完成）': 'posts/2017-12-19-HTTP11-Status-Code-Definitions-zh.md'
        - 'CentOS中通过Nginx和uWSGI部署Flask项目': 'posts/2017-08-01-Nginx_uWSGI_Flask_in_CentOS.md'
        - '使用Python的smtplib和email发送邮件': 'posts/2017-04-09-Use-smtplib-and-email-in-python-to-send-email.md'
        - 'C语言上机心得': 'posts/2016-12-30-C-study.md'
        - 'Markdown语法基础': 'posts/2016-11-13-The-base-of-grammar-in-Markdown.md'
        - '从冯·诺依曼体系结构起航': 'posts/2016-10-22-John-Von-Nouma.md'
    - Repost:
        - '<b>转载文章 - 导读</b>': 'repost/index.md'
        - 'HTTP/1.1 - Status Code Definitions': 'repost/2017-12-19-HTTP11-Status-Code-Definitions-en.md'
    - Review of SS::STA:
        - '<b>SS:STA活动回顾 - 导读</b>': 'sssta/index.md'
        - 'Web 2017下半年活动内容清单': 'sssta/2018-01-19-SSSTA-Web-list2017.md'
        - 'Web4.0 - 前端页面的布局': 'sssta/2017-12-03-SSSTA-Web4.0.md'
        - 'Web3 - Python复习': 'sssta/2017-12-03-SSSTA-Web3.md'
        - 'Web2.0 - HTML与CSS入门': 'sssta/2017-11-19-SSSTA-Web2.0.md'
        - 'Web1 - Web应用概论': 'sssta/2017-11-12-SSSTA-Web1.md'
        - 'Python入门2': 'sssta/2017-10-08-SSSTA-Python2.md'
        - '在GitHub上通过Jekyll搭建个人博客': 'sssta/2017-10-08-SSSTA-Blog.md'
        - 'Python入门1': 'sssta/2017-09-29-SSSTA-Python1.md'
    - Boring:
        - '<b>无聊的内容 - 导读</b>': 'boring/index.md'
        - '虹吸壶冲泡咖啡': 'boring/2018-03-03-siphon.md'
        - 'IKBC Poker2 加灯历程': 'boring/2018-01-20-lighted-poker2.md'
    - Projects:
        - '<b>垃圾代码 - 导读</b>': 'projects/index.md'
        - '生命游戏': 'projects/2017-04-30-Project-Game_or_Life.md'
        - '概率神教 - 优秀的问题解决方案': 'projects/2017-11-19-Project-Coin.md'
    - Donate: 'donate.md'

# Build directories
theme:
    name: 'material'
    language: 'zh'
    logo:
        icon: 'code'
    palette:
        primary: 'teal'
        accent: 'teal'
#docs_dir: 'docs'
#site_dir: 'site'
#extra_css: []
#extra_javascript: []
#extra_templates: []
extra:
    search:
        language: 'en, jp'
    repo_icon: 'github'

# Preview controls
#use_directory_urls: true
#strict: false
dev_addr: 0.0.0.0:80

# Formatting options
markdown_extensions: ['admonition', 'markdown_newtab']
#plugins: ['search']
